### ISSUE TITLE
Random sampling

### ISSUE THREAD

**Issue by AllanLRH** [fastforwardlabs/anomaly_detection#3]
First, thank you for the blog post and code, I enjoyed reading it!

I'm curious about this line of code, where you select a random subset of the points which you proceed to plot:
`thinned_points = np.array([n in np.random.choice(N, 300) for n in range(N)])`.
It seems to me that the same could be achieved by just using 
`thinned_points = np.random.rand(N) < 300.0/N`
Both creates a mask randomly selecting roughly 300/N samples from the ensemble... or am I missing something?

**Comment by nsfinkelstein** [comment]
@AllanLRH Glad you enjoyed it, and thanks for the pull request!

There's no reason that wouldn't work.  I think I'd prefer something that plots a deterministic number of points; I'm sure there's a neater way of achieving that as well.  Open to a pull request in either case!
